"use client";

import dynamic from "next/dynamic";
import Image from "next/image";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowUpRight, Code2, Mail, Menu, Moon, Sun, X } from "lucide-react";
import { projects, services, techGroups } from "@/lib/control-room-data";
import { useWorldStore } from "@/lib/world-state";
import Terminal from "./Terminal";

const Scene = dynamic(() => import("./Scene"), { ssr: false, loading: () => <div className="scene-loading">INITIALIZING ENVIRONMENT</div> });
const nav = [["01", "SERVICES", "services"], ["02", "PROJECTS", "projects"], ["03", "ENGINEERING", "engineering"], ["04", "ABOUT", "about"], ["05", "CONTACT", "contact"]] as const;

export default function ControlRoom() {
  const [dev, setDev] = useState(false); const [menu, setMenu] = useState(false); const [progress, setProgress] = useState(0); const [inspect, setInspect] = useState<(typeof projects)[number] | null>(null); const [coreActive, setCoreActive] = useState(false); const [lightMode, setLightMode] = useState(false);
  const emit = useWorldStore(s => s.emit); const worldMode = useWorldStore(s => s.mode); const activity = useWorldStore(s => s.networkActivity);
  useEffect(() => { const onScroll = () => setProgress(Math.min(100, Math.round(window.scrollY / Math.max(1, document.body.scrollHeight - innerHeight) * 100))); onScroll(); addEventListener("scroll", onScroll, { passive: true }); return () => removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { setLightMode(sessionStorage.getItem("webdz-theme") === "light"); }, []);
  useEffect(() => { sessionStorage.setItem("webdz-theme", lightMode ? "light" : "dark"); }, [lightMode]);
  useEffect(() => { const sections = ["services", "projects", "engineering", "contact"].map(id => document.getElementById(id)).filter(Boolean) as Element[]; const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) emit({type:"SECTION_ENTER", mode:entry.target.id as "services" | "projects" | "engineering" | "contact"}); }), {threshold:.35}); sections.forEach(x=>observer.observe(x)); return ()=>observer.disconnect(); }, [emit]);
  const go = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMenu(false); };
  return <div className="control-room" data-theme={lightMode ? "light" : "dark"} onPointerMove={(e) => { document.documentElement.style.setProperty("--mx", `${e.clientX / innerWidth - .5}`); document.documentElement.style.setProperty("--my", `${e.clientY / innerHeight - .5}`); }}>
    <Scene lightMode={lightMode} onNodeClick={(id) => { emit({type:"NODE_SELECTED",id}); go(id); }} coreActive={coreActive} onCoreClick={() => { setCoreActive(true); emit({type:"CORE_ACTIVATED"}); window.setTimeout(() => go("services"), 650); }} />
    <header className="cr-nav"><button className="wordmark" onClick={() => go("top")} aria-label="WEB DZ home"><Image src="/Images/logo.png" alt="WEB DZ Services" width={420} height={105} priority /></button><nav>{nav.map(([n, l, id]) => <button key={id} onClick={() => go(id)}><small>{n}</small>{l}</button>)}</nav><button className="theme-button" onClick={() => setLightMode(x => !x)} aria-label={`Switch to ${lightMode ? "dark" : "light"} mode`}><Sun/><Moon/><span>{lightMode ? "DARK" : "LIGHT"}</span></button><button className="dev-button" onClick={() => setDev(!dev)} aria-pressed={dev}>[ {dev ? "EXIT" : "DEV" } MODE ]</button><button className="menu-button" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? <X/> : <Menu/>}</button></header>
    {menu && <div className="mobile-nav">{nav.map(([n,l,id]) => <button key={id} onClick={() => go(id)}><small>{n}</small>{l}</button>)}</div>}
    <aside className="progress"><span>SCROLL / {String(progress).padStart(2,"0")}</span><i><b style={{height:`${progress}%`}}/></i></aside>
    {dev && <aside className="dev-panel"><span>SYSTEM DIAGNOSTICS / {worldMode.toUpperCase()}</span>{["FRONTEND", "BACKEND", "DATABASE", "REALTIME", "APIs", "DEPLOYMENT"].map(x => <p key={x}>{x}<b>ONLINE</b></p>)}<p>NETWORK<b>{Math.round(activity*100)}%</b></p><p>PARTICLES<b>260</b></p></aside>}
    <main id="top">
      <section className="hero section-shell"><div className="hero-copy"><p className="eyebrow">SYSTEM / WEB-DZ <em/> STATUS: ONLINE</p><p className="lede">We design and build focused digital systems — from polished web products to connected realtime applications.</p><div className="hero-actions"><button className="cta" onClick={() => go("projects")}>ENTER PROJECTS <ArrowUpRight/></button><button className="text-button" onClick={() => go("services")}>EXPLORE SYSTEM <ArrowDown/></button></div></div><button className={`core-trigger ${coreActive ? "is-active" : ""}`} onClick={() => {setCoreActive(true); emit({type:"CORE_ACTIVATED"}); window.setTimeout(() => go("services"), 650)}} aria-pressed={coreActive}><b/><span>{coreActive ? "SYSTEM ACTIVE" : "WEB DZ"}</span><i>{coreActive ? "NETWORK UNLOCKED" : "CLICK TO ACTIVATE"}</i></button><div className="hero-meta"><span>NODE: ALG-01</span><span>01 / 05</span></div></section>
      <section id="services" className="section-shell services-section"><SectionHead number="01" title="SERVICES" copy="Capabilities arranged for real product work — clear interfaces, durable systems, and considered delivery."/><div className="service-grid">{services.map(s => <article className="service-card" key={s.id}><span>{s.index} / {s.short}</span><h3>{s.name}</h3><p>{s.detail}</p><code>{s.stack}</code></article>)}</div></section>
      <section id="projects" className="section-shell projects-section"><SectionHead number="02" title="PROJECT LAB" copy="A selection of systems and experiences built for specific businesses and workflows."/><div className="project-grid">{projects.map((p,i) => <article className={`project-card ${p.shape}`} key={p.code} onClick={() => {setInspect(p);emit({type:"PROJECT_INSPECT_OPEN",id:p.code})}} tabIndex={0} onKeyDown={(e) => {if(e.key === "Enter"){setInspect(p);emit({type:"PROJECT_INSPECT_OPEN",id:p.code})}}}><div className="project-visual"><i/><i/><span>{String(i+1).padStart(2,"0")}</span></div><div><p>{p.code} / {p.type}</p><h3>{p.name}</h3><p className="project-desc">{p.desc}</p><div className="tags">{p.tech.map(t => <span key={t}>{t}</span>)}</div><button className="inspect-button">INSPECT SYSTEM <ArrowUpRight/></button></div></article>)}</div></section>
      <section id="engineering" className="section-shell engineering-section"><SectionHead number="03" title="ENGINEERING" copy="A practical technical toolkit chosen around the needs of each project."/><div className="engineering-layout"><div className="network"><span>CLIENT</span><i/><span>SERVER</span><i/><span>DATABASE</span><b/><b/><b/></div><div className="tech-list">{techGroups.map(([title,items],i) => <article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{items}</p></article>)}</div></div></section>
      <section id="about" className="section-shell about-section"><SectionHead number="04" title="SYSTEM HISTORY" copy="An independent practice, built incrementally around meaningful client work."/><ol className="timeline"><li><b>2023</b><div><span>FREELANCE / DIGITAL SOLUTIONS</span><p>WEB DZ begins building tailored websites and digital experiences.</p></div></li><li><b>2024</b><div><span>PROJECTS / APPLICATIONS / CLIENT SOLUTIONS</span><p>Expanding into connected applications, business workflows, and product-focused delivery.</p></div></li><li><b>NOW</b><div><span>ENGINEERING BETTER DIGITAL SYSTEMS</span><p>Combining web, mobile, data, APIs and practical AI integration where it creates value.</p></div></li></ol></section>
      <section id="contact" className="section-shell contact-section"><p className="eyebrow">05 / COMMUNICATION NODE <em/> READY</p><h2>LET’S BUILD<br/><span>SOMETHING.</span></h2><p>Web development · Mobile applications · Desktop applications · AI integration · Custom digital solutions.</p><div className="contact-actions"><a className="cta" href="mailto:aben7400@gmail.com">START A CONVERSATION <Mail/></a><a href="tel:+213699745419">+213 558 982 625</a><span>SIDI BEL ABBÈS, ALGERIA</span></div><footer>© {new Date().getFullYear()} WEB DZ SERVICES <span>BUILT FOR THE NEXT SYSTEM.</span></footer></section>
    </main><button className="terminal-toggle" onClick={() => emit({type:"TERMINAL_OPEN"})}>COMMAND /_</button><Terminal />{inspect && <div className="inspect-mode" role="dialog" aria-modal="true"><button className="inspect-close" onClick={() => {setInspect(null);emit({type:"PROJECT_INSPECT_CLOSE"})}}>CLOSE <X/></button><div className={`inspect-object ${inspect.shape}`}><i/><i/><i/></div><div className="inspect-hud"><p>INSPECT MODE / {inspect.code}</p><h2>{inspect.name}</h2><span>{inspect.type}</span><p className="inspect-description">{inspect.desc}</p><div className="tags">{inspect.tech.map(t=><span key={t}>{t}</span>)}</div><div className="hud-status"><span>ENVIRONMENT</span><b>ONLINE</b><span>MODULES</span><b>ACTIVE</b><span>DATA LINK</span><b>STABLE</b></div><a className="cta" href={inspect.href} target={inspect.href.startsWith("http") ? "_blank" : undefined} rel="noreferrer">OPEN PROJECT <ArrowUpRight/></a></div></div>}
  </div>;
}
function SectionHead({number,title,copy}:{number:string,title:string,copy:string}) { return <div className="section-head"><p>{number} / SECTOR</p><h2>{title}</h2><span>{copy}</span></div>; }
