"use client";
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { Float, Html, Line, Stars } from "@react-three/drei";
import { useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { useWorldStore } from "@/lib/world-state";

const nodes = [{n:"AI",p:[0,2.6,0],k:"ai"},{n:"WEB",p:[-3,.7,0],k:"web"},{n:"MOBILE",p:[3,.7,0],k:"mobile"},{n:"REALTIME",p:[-2.5,-2,0],k:"realtime"},{n:"DESKTOP",p:[2.5,-2,0],k:"desktop"},{n:"PROJECTS",p:[0,-3.4,0],k:"api"}] as const;
function Particles(){const ref=useRef<THREE.Points>(null!);const seed=useMemo(()=>Array.from({length:260},()=>new THREE.Vector3((Math.random()-.5)*13,(Math.random()-.5)*10,(Math.random()-.5)*5)),[]);const pos=useMemo(()=>new Float32Array(seed.length*3),[seed]);useFrame(({clock,mouse})=>{const c=new THREE.Vector3(mouse.x*4,mouse.y*3,0),t=clock.getElapsedTime();seed.forEach((b,i)=>{const p=b.clone().add(new THREE.Vector3(Math.sin(t+i)*.07,Math.cos(t*.7+i)*.07,0));const d=p.clone().sub(c),l=Math.max(.6,d.length());p.addScaledVector(d.normalize(),.12/l);pos.set([p.x,p.y,p.z],i*3)});ref.current.geometry.attributes.position.needsUpdate=true});return <points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" args={[pos,3]}/></bufferGeometry><pointsMaterial size={.026} color="#62e9f8" transparent opacity={.72}/></points>}
function CameraController(){const {camera}=useThree();const mode=useWorldStore(s=>s.mode),selected=useWorldStore(s=>s.selectedObject);useFrame(({mouse})=>{const targets:Record<string,THREE.Vector3>={ai:new THREE.Vector3(0,2.6,0),web:new THREE.Vector3(-3,.7,0),mobile:new THREE.Vector3(3,.7,0),realtime:new THREE.Vector3(-2.5,-2,0),projects:new THREE.Vector3(0,-3.4,0)};const look=targets[selected||""]||new THREE.Vector3();const distance=mode==="inspect"?5:selected?6.5:8;const desired=new THREE.Vector3(look.x*.18+mouse.x*.22,look.y*.12+mouse.y*.18,distance);camera.position.lerp(desired,.035);camera.lookAt(look)});return null}
function Connection({from,to,color="#126271"}:{from:[number,number,number],to:[number,number,number],color?:string}){const activity=useWorldStore(s=>s.networkActivity);const packet=useRef<THREE.Mesh>(null!);const curve=useMemo(()=>new THREE.CatmullRomCurve3([new THREE.Vector3(...from),new THREE.Vector3((from[0]+to[0])/2,(from[1]+to[1])/2+.35,-.2),new THREE.Vector3(...to)]),[from,to]);useFrame(({clock})=>{const t=(clock.getElapsedTime()*(.18+activity*.55))%1;packet.current.position.copy(curve.getPoint(t))});return <><Line points={curve.getPoints(18)} color={color} transparent opacity={.24+activity*.35}/><mesh ref={packet}><sphereGeometry args={[.045,8,8]}/><meshBasicMaterial color={activity>.8?"#ffb547":"#00e5ff"}/></mesh></>}
function Core({active,onClick}:{active:boolean,onClick:()=>void}){const ref=useRef<THREE.Group>(null!);const [hot,setHot]=useState(false);useFrame(({clock,mouse})=>{const s=active?1.6:hot?1.18:1;ref.current.scale.lerp(new THREE.Vector3(s,s,s),.07);ref.current.rotation.y=clock.getElapsedTime()*.15+mouse.x*.25;ref.current.rotation.x=mouse.y*.15});return <group ref={ref} onClick={onClick} onPointerOver={()=>{setHot(true);document.body.style.cursor="pointer"}} onPointerOut={()=>{setHot(false);document.body.style.cursor="default"}}><Float speed={1.3} rotationIntensity={.25}><mesh rotation={[.78,.78,0]}><octahedronGeometry args={[1.25,1]}/><meshStandardMaterial color="#071b22" emissive="#00b8cf" emissiveIntensity={hot||active?1.7:.6} metalness={.8} wireframe/></mesh><mesh><icosahedronGeometry args={[.74,1]}/><meshStandardMaterial color="#00e5ff" emissive="#007789" emissiveIntensity={2} transparent opacity={.32}/></mesh>{[-1,0,1].map((x,i)=><mesh key={i} rotation={[Math.PI/2,0,i*.6]} position={[0,0,x*.12]}><torusGeometry args={[1.45+i*.12,.012,8,50]}/><meshBasicMaterial color={hot||active?"#ffb547":"#00e5ff"}/></mesh>)}</Float></group>}
function Shape({k,hot}:{k:string,hot:boolean}){const mat=<meshStandardMaterial color={hot?"#ffb547":"#00e5ff"} emissive={hot?"#bd7619":"#006c7d"} emissiveIntensity={hot?2:1} wireframe/>;if(k==="mobile")return <mesh><boxGeometry args={[.32,.64,.08]}/>{mat}</mesh>;if(k==="desktop")return <group><mesh position={[0,.08,0]}><boxGeometry args={[.6,.38,.06]}/>{mat}</mesh><mesh position={[0,-.2,0]}><boxGeometry args={[.35,.04,.04]}/>{mat}</mesh></group>;if(k==="web")return <group>{[-.17,0,.17].map(y=><mesh key={y} position={[0,y,0]}><boxGeometry args={[.55,.05,.04]}/>{mat}</mesh>)}</group>;if(k==="ai")return <group>{[-.23,0,.23].map(x=><mesh key={x} position={[x,Math.abs(x)*.5,0]}><sphereGeometry args={[.09,8,8]}/>{mat}</mesh>)}<Line points={[[-.23,.12,0],[0,0,0],[.23,.12,0]]} color="#00e5ff"/></group>;if(k==="realtime")return <group>{[-.24,.24].map(x=><mesh key={x} position={[x,0,0]}><sphereGeometry args={[.1,10,10]}/>{mat}</mesh>)}<Line points={[[-.24,0,0],[.24,0,0]]} color="#00e5ff"/></group>;return <mesh><torusGeometry args={[.28,.06,8,20]}/>{mat}</mesh>}
function Node({n,p,k,onClick}:{n:string,p:readonly number[],k:string,onClick:(x:string)=>void}){const ref=useRef<THREE.Group>(null!);const [hot,setHot]=useState(false),[drag,setDrag]=useState(false);const emit=useWorldStore(s=>s.emit);const home=useMemo(()=>new THREE.Vector3(...p),[p]);useFrame(({mouse,clock})=>{const target=drag?new THREE.Vector3(mouse.x*4,mouse.y*3,0):new THREE.Vector3(home.x+Math.sin(clock.getElapsedTime()+home.x)*.12,home.y+Math.cos(clock.getElapsedTime()+home.y)*.1,0);ref.current.position.lerp(target,drag?.13:.035);ref.current.rotation.y+=hot?.024:.007});return <group ref={ref} position={p as [number,number,number]} onPointerDown={(e)=>{e.stopPropagation();if(n==="REALTIME")setDrag(true)}} onPointerUp={(e)=>{e.stopPropagation();setDrag(false)}} onClick={(e)=>{e.stopPropagation();if(n!=="REALTIME")onClick(n==="PROJECTS"?"projects":"services")}} onPointerOver={()=>{setHot(true);emit({type:"NODE_HOVER",id:n.toLowerCase()});document.body.style.cursor=n==="REALTIME"?"grab":"pointer"}} onPointerOut={()=>{setHot(false);emit({type:"NODE_HOVER",id:null});if(!drag)document.body.style.cursor="default"}}><Float speed={1.5} rotationIntensity={.15} floatIntensity={.4}><Shape k={k} hot={hot}/></Float><Line points={[[0,0,0],[-p[0]*.31,-p[1]*.31,0]]} color={hot?"#ffb547":"#126271"} transparent opacity={.7}/><Html distanceFactor={9} position={[0,-.42,0]} center><div className={`node-label ${hot?"hot":""}`}><b>{n}</b><span>{n==="REALTIME"?(drag?"LINKING...":"GRAB TO LINK"):"DISCOVER MODULE"}</span></div></Html></group>}
function World({onNodeClick,coreActive,onCoreClick,lightMode}:{onNodeClick:(x:string)=>void,coreActive:boolean,onCoreClick:()=>void,lightMode:boolean}){return <><CameraController/><ambientLight intensity={lightMode?.9:.45}/><pointLight color="#00a9c0" intensity={lightMode?10:16} distance={10}/><pointLight position={[5,-4,2]} color="#d68b24" intensity={lightMode?4:6}/><Stars radius={18} depth={12} count={420} factor={2} saturation={0} fade speed={.35}/><Particles/><Connection from={[0,2.6,0]} to={[0,-3.4,0]}/><Connection from={[-3,.7,0]} to={[-2.5,-2,0]}/><Connection from={[3,.7,0]} to={[-2.5,-2,0]}/><Connection from={[0,2.6,0]} to={[-3,.7,0]}/><Core active={coreActive} onClick={onCoreClick}/>{nodes.map(x=><Node key={x.n} n={x.n} p={x.p} k={x.k} onClick={onNodeClick}/>)}</>}
export default function Scene({onNodeClick,coreActive,onCoreClick,lightMode}:{onNodeClick:(x:string)=>void,coreActive:boolean,onCoreClick:()=>void,lightMode:boolean}){return <div className="scene" aria-hidden="true"><Canvas dpr={[1,1.5]} camera={{position:[0,0,8],fov:46}} gl={{antialias:true,alpha:true,powerPreference:"high-performance"}}><fog attach="fog" args={[lightMode?"#e9f2f4":"#05070a",7,18]}/><World onNodeClick={onNodeClick} coreActive={coreActive} onCoreClick={onCoreClick} lightMode={lightMode}/></Canvas></div>}
